### PR TITLE
support for Swift3 with Xcode8GM

### PR DESCRIPTION
**Pull request by sstadelman**
This updates the syntax for Swift3, with Xcode-beta6 language updates.

The target `Use Legacy Swift Language Version` build setting is set to `NO`.

Validated in internal development for ~2 weeks.

### CODE REVIEW

**Comment by esetnik** [comment]
@sstadelman have you seen any issues like:

**Comment by sstadelman** [comment]
@esetnik no, I haven't seen that... is your framework search path set correctly?

**Comment by esetnik** [comment]
@sstadelman are you using Cocoapods or carthage to manage your NibDesignable dependency?

**Comment by esetnik** [comment]
@mbogh can you rerun the travis tests? They failed with a strange error and the tests pass locally.

**Comment by ikesyo** [comment]
Using `xcodebuild build-for-testing test-without-building` should stabilize the CI builds on Travis with Xcode 8.

**Comment by esetnik** [comment]
@mbogh can we get this merged?

**Comment by mbogh** [comment]
If we could get Travis happy again, I am all for this PR :)

**Comment by esetnik** [comment]
@mbogh the tests are actually passing it's just that travis was flakey when @sstadelman uploaded his build. You can see a recent passed test run using the same commit at https://travis-ci.org/esetnik/NibDesignable/jobs/160884386. Please rerun the tests on travis and they should pass this time.

**Comment by ikesyo** [comment]
See my comment above for the test failure: https://github.com/mbogh/NibDesignable/pull/42#issuecomment-246109828

**Comment by mbogh** [comment]
Travis build has been restart lets see what the verdict is :)

**Comment by mbogh** [comment]
@farzadshbfn do you have any objections?

**Comment by farzadshbfn** [comment]
@mbogh no, I had objections against other PR's. this one's so clean 👍

**Pull request merged**
