### PR TITLE
Update to Swift 3

### PR DESCRIPTION
**Pull request by chrisfsampaio**

### CODE REVIEW

**Comment by mbogh** [comment]
Hi @chrisfsampaio,

this should probably be put onto a separate branch until Swift 3/Xcode 8 goes final.

**Comment by chrisfsampaio** [comment]
Hello @mbogh,
Agreed, if you create the branch I can recreate the PR against it.

**Comment by mbogh** [comment]
It has been done, the `.travis.yml` should also be updated so we can get a green build 😄

**Comment by chrisfsampaio** [comment]
👍 Closing in favor of #38

**Pull request closed without merging**
