### PR TITLE
updated to swift 3.0

### PR DESCRIPTION
**Pull request by appoulsen**
Updated from swift 2.3 to swift 3.0

### CODE REVIEW

**Comment by farzadshbfn** [comment]
@appoulsen why did you change `setubNib()` from private to public? 🤔

**Comment by farzadshbfn** [comment]
I think what you're looking for is `fileprivate` @appoulsen

**Comment by appoulsen** [comment]
fileprivate wouldn't work cause if someone was to implement there own nibdesignable with the nibdeisgnableprotocol. They wouldn't be able to acces the function. Alternative it could be internal that should work. Or completely shutting out developers with making the nibdesignableprotocol fileprivate

**Comment by mbogh** [comment]
Pull Request #42 has been merged, so I am closing this one.

**Pull request closed without merging**
