### PR TITLE
Upgrade to Swift 2.3

### PR DESCRIPTION
**Pull request by brentleyjones**
No code change, but build setting needed in order to get Carthage to build correctly (ie. not Swift 3).

### CODE REVIEW

**Comment by mbogh** [comment]
Seems that xctool might not be ready for Xcode 2.3

**Comment by brentleyjones** [comment]
I dislike xctool personally. Also, another project that accepted my Swift 2.3 changes reverted to xcodebuild: https://github.com/SwiftyBeaver/SwiftyBeaver/commit/8bb96c0b56e4bd36efa4844e1fb89428ed800f01

**Comment by mbogh** [comment]
You are more than welcome to switch to xcodebuild 🦄

Hilsen
Morten Bøgh

**Comment by farzadshbfn** [comment]
Closing in favor of #36

**Comment by farzadshbfn** [comment]
Closing in favor of #36

**Pull request closed without merging**
